"""extend hospital profile fields, rejection reason

Revision ID: 9bb58f628e57
Revises: c5488d5c6b03
Create Date: 2026-09-01 12:50:57.057079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb58f628e57'
down_revision: Union[str, None] = 'c5488d5c6b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


organization_type_enum = sa.Enum(
    'hospital', 'clinic', 'blood_center', 'medical_center', 'other', name='organization_type'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    organization_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('hospitals', sa.Column('organization_type', organization_type_enum, nullable=True))
    op.add_column('hospitals', sa.Column('organization_type_other', sa.String(length=255), nullable=True))
    op.add_column('hospitals', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('hospitals', sa.Column('representative_name', sa.String(length=255), nullable=True))
    op.add_column('hospitals', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('hospitals', sa.Column('phone_number', sa.String(length=16), nullable=True))
    op.add_column('hospitals', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.drop_column('hospitals', 'contact_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('contact_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('hospitals', 'rejection_reason')
    op.drop_column('hospitals', 'phone_number')
    op.drop_column('hospitals', 'contact_email')
    op.drop_column('hospitals', 'representative_name')
    op.drop_column('hospitals', 'address')
    op.drop_column('hospitals', 'organization_type_other')
    op.drop_column('hospitals', 'organization_type')
    organization_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
