"""add donor phone_number and has_never_donated

Revision ID: c5488d5c6b03
Revises: 8e56adcca5a5
Create Date: 2026-08-20 07:53:52.619908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5488d5c6b03'
down_revision: Union[str, None] = '8e56adcca5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'donor_profiles',
        sa.Column('has_never_donated', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('donor_profiles', sa.Column('phone_number', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donor_profiles', 'phone_number')
    op.drop_column('donor_profiles', 'has_never_donated')
    # ### end Alembic commands ###
